name: container image release

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: go build
      run: |
        go build ./...

  deploy:
    runs-on: ubuntu-latest

    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: prepare version strings
        env:
          DOCKERHUB_ORG: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo DOCKERHUB_REPOSITORY=${DOCKERHUB_ORG}/${GITHUB_REPOSITORY#*/} >> $GITHUB_ENV
          echo VERSION_TAG=${GITHUB_REF#$"refs/tags/v"} >> $GITHUB_ENV

      - name: Print Version
        run: |
          echo "Version: $VERSION_TAG"
          echo "Dockerhub Repository: $DOCKERHUB_REPOSITORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}


      - name: checkout
        uses: actions/checkout@v4

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{env.DOCKERHUB_REPOSITORY}}:${{env.VERSION_TAG}}
            ${{env.DOCKERHUB_REPOSITORY}}:latest
          build-args: |
            ${{steps.version_step.outputs.version}}

